export const API_KEY = process.env.PLASMO_PUBLIC_GROQ_API_KEY
export const API_PREFIX = process.env.PLASMO_PUBLIC_API_PREFIX
export const API_USER_ID = process.env.PLASMO_PUBLIC_API_USER_NAME
export const QUESTION_SUGGESTION_SYSTEM_PROMPT = process.env.PLASMO_PUBLIC_QUESTION_SUGGESTION_SYSTEM_PROMPT
export const AUDIO_TO_TEXT_INTERVAL_TIME = process.env.PLASMO_PUBLIC_API_AUDIO_TO_TEXT_INTERVAL_TIME ?? 5000
export const FETCH_SUGGESTION_INTERVAL_TIME = process.env.PLASMO_PUBLIC_API_FETCH_SUGGESTION_INTERVAL_TIME ?? 10000
